backend:
<<<<<<< HEAD
  name: test-repo

media_folder: data/images
public_folder: /images

collections:
  - name: 'items'
    label: 'Items'
    folder: 'data/items'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Abbreviation', name: 'abbreviations', widget: 'string' }
=======
  name: git-gateway
  branch: master
>>>>>>> 0b3309bb0f8e9feaa0eede31b41094618f3aa634
