backend:
  name: git-gateway

media_folder: data/images
public_folder: /images

collections:
  - name: 'items'
    label: 'Items'
    folder: 'data/items'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Abbreviation', name: 'abbreviations', widget: 'string' }
